https://ja.wikipedia.org/wiki/%E9%81%B8%E6%8C%99
http://www.yomiuri.co.jp/election/shugiin/2017/kaihyou/ya13.html
http://www.soumu.go.jp/senkyo/senkyo_s/
https://www.city.shinjuku.lg.jp/kusei/index10.html
http://www.asahi.com/senkyo/senkyo2017/kaihyo/
http://www.asahi.com/senkyo/senkyo2017/kaihyo/A23.html
http://www.sankei.com/politics/newslist/election-n1.html
https://mainichi.jp/senkyo/
https://www.nhk.or.jp/senkyo/
https://www.city.shibuya.tokyo.jp/kusei/politics/